### ISSUE TITLE
A bug in cpu implementation.

### ISSUE THREAD

**Issue by yelantf** [harveyslash/PatchMatch#2]
In PatchMatchOrig.py, the Line 55
`dx1 = min(self.A.shape[0] - ax, self.B.shape[0] - bx, dx1)`
and Line 57
`dy1 = min(self.A.shape[1] - ay, self.B.shape[1] - by, dy1)`
seems wrong. I think it should be
`dx1 = min(self.A.shape[1] - ax, self.B.shape[1] - bx, dx1)`
and
`dy1 = min(self.A.shape[0] - ay, self.B.shape[0] - by, dy1)`,
am I right?

**Comment by CLT29** [comment]
This seems right to me. Without this fix, the code crashes on some inputs.
